@baseUrl=http://localhost:8080/api

### Signup
POST {{baseUrl}}/join HTTP/1.1
Content-Type: application/json

{
  "username": "comit05",
  "password": "comit05",
  "phoneNumber": "01000000005",
  "studentId": "2020000005",
  "email": "comit05@gmail.com"
}

