@baseUrl=http://localhost:8080/api

### Member Login (comit01 ~ comit04)
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "comit01@gmail.com",
  "password": "comit01"
}

> {%
    client.global.set("access_token", response.headers.valueOf('access'));
    client.global.set("refresh_token", response.headers.valuesOf("Set-Cookie")[0])
%}

### Admin Login
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin"
}

> {%
    client.global.set("access_token", response.headers.valueOf('access'));
    client.global.set("refresh_token", response.headers.valuesOf("Set-Cookie")[0]);
%}